# Generated by Django 5.2.8 on 2025-11-30 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_footertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.ForeignKey(blank=True, help_text='Choose which footer snippet to display globally', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.footertext')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
