# Generated by Django 5.2.8 on 2025-11-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_footerconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.DeleteModel(
            name='FooterConfig',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
