# Generated by Django 5.2.8 on 2025-11-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_footertext_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='custom_text',
            field=models.CharField(default='Your custom footer text here', max_length=255),
        ),
    ]
