# Generated by Django 5.2.8 on 2025-11-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_navigationsettings_custom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hide_footer',
            field=models.BooleanField(default=False),
        ),
    ]
